### ISSUE TITLE
Cache Problem in files listing

### ISSUE THREAD

**Issue by MohsinQK** [fnagel/pluploadfe#12]
If a upload new Files to the directory they would not show until I remove the cache from the backend.

**Comment by fnagel** [comment]
Sorry for the late response. Seems I've missed this issue. 

Any news on this? Still an issue?

**Comment by MohsinQK** [comment]
I have not tested that, it's like almost a year ago :)

**Comment by fnagel** [comment]
Thanks for the fast answer. I will close this for now as I'm not able to reproduce. Please reopen if needed!
