### ISSUE TITLE
File upload is not reacting.

### ISSUE THREAD

**Issue by TGOTFC** [fnagel/pluploadfe#14]
The extension works perfect until a file is added. When the FE user clicks on "Start Upload" nothing happens, and the File is not uploaded.

Since there is no pop-up error I looked up the Console, there it just says "p.on is not a function" .

If you need additional info please reply, thanks in advance, awesome tool if I can get it working!!!

![notafunction](https://user-images.githubusercontent.com/48449871/54142386-da655c80-4427-11e9-820c-cd4f4a7cfa2c.PNG)

**Comment by fnagel** [comment]
Sounds like JS ordering issue. Like jQuery is not available when the plupload JS is called. 

Is there a demo I can access to check?

**Comment by TGOTFC** [comment]
*Edited the link*

Frontend Demo is available under result21.retail-Tools.de<http://result21.retail-Tools.de>

User test04
PW test04

Thank you for the quick reply!

**Comment by fnagel** [comment]
Seems like the jQuery version is waaaaay to old (version 1.3.2 is about 10 years old). Try using at least 1.9.x

**Comment by TGOTFC** [comment]
Ok, thanks a lot for your time, I think we are using this old version of jQuery because of some issues with other pretty old extensions, now we have run officially out of excuses to update. Thank you so much for your time, will donate for sure on your Paypal page.

**Comment by fnagel** [comment]
> Ok, thanks a lot for your time, I think we are using this old version of jQuery because of some issues with other pretty old extensions, 

Glad I could help. Let me know if updating jQuery version really solved the issue, but I'm pretty sure about it.

>now we have run officially out of excuses to update. 

:-D

> Thank you so much for your time, will donate for sure on your Paypal page.

That would be great! Take a look here for more options: https://www.felixnagel.com/donate

**Comment by TGOTFC** [comment]
Ahhh I just remembered that I do not have a Paypal Account anymore, I used the contact formular on your homepage, pls just send me the bvank account data and I will wire you the donation.

Thanks

**Comment by fnagel** [comment]
Amazon Wishlist is another option: https://www.amazon.de/wishlist/2QVBG87FBTKQX

What's your name? I'm not able to find a message sent by my website contact form.

**Comment by TGOTFC** [comment]
The name is Alexander Schu, typed it in 5 minutes ago. But save the effort, I'm gonna pick something from your Amazon wishlist :)

**Comment by TGOTFC** [comment]
Amazon wishlist (cannot send the package directly to you) does not work either, pls send me the bank account to alexander.schu@bade.de  

Thank you.
