### ISSUE TITLE
Version 5.0,  TYPO3 11.5 Setting upload_path for "Plupload Configuration"

### ISSUE THREAD

**Issue by TokeHerkild** [fnagel/pluploadfe#21]
Cannot change upload path from /fileadmin, eg: no 'fileadmin/uploads' or 'fileadmin/anotherDir'

Getting JS error: "Uncaught ReferenceError: el is not defined" In FormEngine.js line: 168

**Comment by TokeHerkild** [comment]
It's an issue with TCA::type == folder, AND size=1, in TYPO3 11.5 default element isn't deleted prior to adding new item, is this a TYPO3 core issue ?

**Comment by fnagel** [comment]
Looks like a new issue as I had sub folders for `fileadmin` defined in existing installations. I've just tested this in a TYPO3 10.4.23 instance without issues. 

Pretty sure this is a core issue (as I'm using default TCA config here) but I was not able to find an existing issue on forge. Would you mind creating one and link it here?

**Comment by TokeHerkild** [comment]
Not an issue, just haven't got around to getting in here. Just me not being in TYPO3 backend usually, and hadn't realized I had to delete the default before I could add a new link. So my bad, sorry for not answering before now.

**Comment by fnagel** [comment]
Ahh okay, so more like a usability issue within the TYPO3 core, right? In this case I would like to close the issue.

Anyway, glad you were able to make it work :-) And don't hesitate to ask questions or ask for fixes / improvements, I'm here to help!
