### ISSUE TITLE
Viewing uploaded files

### ISSUE THREAD

**Issue by AntonMezger** [fnagel/pluploadfe#23]
Hi,
Very good extension. One can upload files to user directories.

 My question is, how the user can view the uploaded files and how to  delete or download them after upload?

**Comment by fnagel** [comment]
Hi @AntonMezger! 

Viewing uploaded files (or download / delete actions) are not in the scope of this extension. For rendering you could use the TYPO3 content element "File Links" (internal key is uploads).

See here for more info:
https://docs.typo3.org/m/typo3/tutorial-editors/main/en-us/ContentElements/CreatingContent/Index.html#typical-page-content 
https://github.com/TYPO3-CMS/fluid_styled_content/blob/11.5/Configuration/TypoScript/ContentElement/Uploads.typoscript

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
