### ISSUE TITLE
TYPO3 12 support

### ISSUE THREAD

**Issue by fnagel** [fnagel/pluploadfe#24]
### Update extension for TYPO3 CMS 12 LTS.  

Release is planned for end of this summer. Hopefully. Any help is appreciated!

WIP Branch: https://github.com/fnagel/pluploadfe/tree/typo3-12

**References**
- https://get.typo3.org/release-notes/12.0.0
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog-12.html
- https://notes.typo3.org/s/EjM2zA7Dr

**Comment by fnagel** [comment]
Extension should be ready. Feedback would be appreciated, please see WIP branch!

**Comment by DL1ndner** [comment]
Tried with TYPO3 12.4.7 on PHP 8.2 and it works like a charm (had to re-include plupload config but that might be connected to my setup). Thank you so much!

**Comment by fnagel** [comment]
@DL1ndner Thanks so much for the feedback. Only one more extension to fix for v12 until I push a TER release!

**Comment by fnagel** [comment]
Version 7.0.0 with support for TYPO3 12 has been released: https://github.com/fnagel/pluploadfe/releases/tag/7.0.0
