### ISSUE TITLE
Your browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.

### ISSUE THREAD

**Issue by wowaTYPO3** [fnagel/pluploadfe#3]
Tried the extension in latest Chrome and Firefox, but got the following message in the frontend:

Your browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.

jQuery 2.1.4 is included.

**Comment by fnagel** [comment]
Could be a thousand things. Probably just a JS error. Do you have a site to take a look at?

Did it work with the version before? TYPO3 version?

**Comment by wowaTYPO3** [comment]
TYPO3 7.6.4, it's my first test with this extension, so I've no experience with former versions

http://spielwiese.typo3-workshop.eu/standard-inhaltselemente/plupload.html

**Comment by fnagel** [comment]
Seems like plupload fails due to a JS error:

```
Uncaught TypeError: jQuery(...).magnificPopup is not a function
```

This looks unrelated to this extension.

**Comment by wowaTYPO3** [comment]
Ahh, thanks for this hint. I saw this error message, but thought, this is probably not the problem, but it was. It seems, there's a conflict with the ext. ag_projects, which I tested in this installation too. Now everything works very well! ;)
