### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by noteven2degrees** [fnagel/pluploadfe#5]
Hey Felix

The pluploadfe is a great extension, saw it is some use cases. Now, I don't get it running at my side:
-- installation via Ext. Manager --> works
-- insert as FE Plugin --> works
-- but what to enter in the Configuration drop-down in the FE Plugin Tab? I found the default config under
[root] / typo3conf / ext / pluploadfe / Configuration / TCA, but how to access it with the FE drop-down?

Thank you for support, Cheers
Christian

**Comment by fnagel** [comment]
You need to create a configuration record. Try the list module to do so!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by noteven2degrees** [comment]
Hallo Felix

Dein Name klingt deutsch, können wir auch so machen.
Leider hat mir Deine Einzeiler-Antwort nicht besonders geholfen, da ich 
kein Typo3-Experte bin. Ich treffe mich in Kürze mit einem Typo3 
Webentwickler und kann mit ihm einige Punkte durchgehen. Konkret habe 
ich keine Ahnung, wie ich einen configuration record wo und warum 
erzeuge.

Danke für die Nachfrage.

Viele Grüsse
Christian

Am 2016-08-13 14:31, schrieb Felix Nagel:

**Comment by fnagel** [comment]
Sorry, die Mail ist mir durchgerutscht. 

Warum: Zur Konfiguration von zB Upload-Pfad, Sicherheit (erlaubte Dateien, nur mit Login, etc.), u.a.
Wo: Im Listen Modul einen neuen Datensatz vom Typ "Pluplod Konfiguration" erzeugen

In den Konfig-Dateien definierst du die Kriterien für den Upload. Diese Datensätze kannst du dann mit dem Plugin verbinden. So kann man an verschiedenen Stellen verschiedenartige Uploads realisieren.

Stell gern noch weitere konkrete Fragen. Schönes WE wünsche ich!

**Comment by fnagel** [comment]
Gibt hierzu noch weitere Rückmeldung?

**Comment by noteven2degrees** [comment]
Tut mir leid, Felix

Habe Deine Nachricht gesehen, ging dann aber unter.
Vielen Dank für Deine Antworten. Ich habe in weiteren Diskussionen mit 
Typo3-Entwicklern meine Anforderungen besser spezifizieren können und 
benötge besagte Extension daher vorerst nicht.

Merci & alles Gute
Christian
