### ISSUE TITLE
Veränderte Ansicht "Neues Inhaltselement"nach update auf v. 1.5.0

### ISSUE THREAD

**Issue by Gorli** [fnagel/pluploadfe#6]
Hallo,

nach einem update auf Version 1.5.0 werden beim anlegen eines "Neues Inhaltselement" im BE nur noch pluploadfe angezeigt. Andere Plugins usw. werden nicht mehr angezeigt - siehe screenshots?!

Vielen Dank

Goarli
![version-1 4 0](https://cloud.githubusercontent.com/assets/4998028/18263982/b9124ba2-740d-11e6-8808-bbbabe51c887.PNG)
![version-1 5 0](https://cloud.githubusercontent.com/assets/4998028/18263983/b912dfea-740d-11e6-989e-c4676a554a0a.PNG)

**Comment by fnagel** [comment]
Confirmed. Issue is caused by `show := addToList(pluploadfe)` within `Configuration/TypoScript/pageTsConfig.ts`.  Removal fixes the issue.

Will be included in next TER version (as soon as #7 is fixed) Thanks for reporting!
