### ISSUE TITLE
Wrong fieldname "realName" in class class.tx_pluploadfe_upload.php

### ISSUE THREAD

**Issue by mec0-de** [fnagel/pluploadfe#8]
Building the upload path with user data doesn´t work with the setting realName. Username works, but I want to use realName.
Looking into the code I found this in the method getUserDirectory:

```
switch ($field) {

			case 'realName':
			case 'username':
				$directory = $record[$field];
				break;
```

The database field for the realName is "name". Could this be the problem?
I´m on typo version 7.6.11

**Comment by fnagel** [comment]
Seems you're right, this looks like an error to me.

@c2po Any idea why you used `realName` here at all? It's existing for BE users, but not for FE users.

Reference:
https://github.com/TYPO3/TYPO3.CMS/blob/2db44c6db901b69f2c45d2b06e618260a10d6e6a/typo3/sysext/frontend/ext_tables.sql#L79
https://github.com/TYPO3/TYPO3.CMS/blob/2db44c6db901b69f2c45d2b06e618260a10d6e6a/typo3/sysext/frontend/Configuration/TCA/fe_users.php#L70

**Comment by fnagel** [comment]
@c2po Any feedback on this issue?

Reference: https://github.com/fnagel/pluploadfe/pull/1

**Comment by fnagel** [comment]
@c2po Any feedback on this one?

**Comment by fnagel** [comment]
Fixed in master. TER release follows within the next hour.
